feat: Add lazy support to available items grid
FlowingCode/TwinColGridAddon pull request #135
Opened 2023-03-03 13:43 UTC by flang

Close #130

2023-03-03 13:51 UTC, javier-godoy commented
Cherrypick https://github.com/FlowingCode/TwinColGridAddon/commit/95499801bf83392e3a5abc99cff0fc19383babb2 for fixing compilation with Vaadin 24 (#133)

2023-03-06 18:26 UTC, paodb commented on src/test/java/com/flowingcode/vaadin/addons/twincolgrid/FilterableDemo.java
> -@DemoSource
Is there a reason why @DemoSource is being removed here?

2023-03-06 18:27 UTC, paodb commented on src/test/java/com/flowingcode/vaadin/addons/twincolgrid/LazyFilterableDemo.java
> +@Route(value = "twincolgrid/lazyfilterable", layout = TwincolDemoView.class)
@DemoSource is missing here

2023-03-06 19:28 UTC, paodb requested changes
See comments

2023-07-24 19:40 UTC, closed without merging